version: '3.4'
services:
  structure_test:
    image: flopes/container-structure-test-docker
    volumes:
      - "./docker/tests/config.yaml:/test-config/tests/config.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: test --image jpnauta/remote-structure-test --config tests/config.yaml