[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[override]]
  name = "github.com/spf13/pflag"
  revision = "583c0c0531f06d5278b7d917446061adc344b5cd"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
